# Site settings
name: Andy von Dohren
title: Andy von Dohren
email: avondohren@gmail.com
description: "Web Application Portfolio"
baseurl: ""
url: "http://andyv.me"

# Social Network settings
github : avondohren
twitter : andyvondohren

# Build settings
markdown: kramdown
permalinks: pretty

# Paginate Info
paginate: 5
paginate_path: "/blog/page:num"

# Settings for analytics helper
# Set 'provider' to the analytics provider you want to use.
# Set 'provider' to false to turn analytics off globally.
#        
analytics :
  provider : google
  google : 
      tracking_id : 'UA-50850712-1'
