# Site settings
name: Andy von Dohren
title: Andy von Dohren
email: avondohren@gmail.com
description: "Web Application Portfolio"
baseurl: "http://andyv.me"
url: "http://andyv.me"

# Social Network settings
github : avondohren
twitter : andyvondohren

# Build settings
markdown: kramdown
permalinks: pretty

paginate: 5
paginate_path: "page:num"
destination: _site/blog
